server:
  port: 9004
spring:
  application:
    name: fegin.application
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
feign:
  hystrix:
    enabled: true

